apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: dvcloud-xyz-tls
spec:
  secretName: dvcloud-xyz
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: dvcloud.xyz
  dnsNames:
    - dvcloud.xyz
    - www.dvcloud.xyz
  acme:
    config:
      - http01:
        incressClass: nginx
        domains:
          - dvcloud.xyz
          - www.dvcloud.xyz